webapp_user:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }

webapp_user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }

webapp_user_new:
    path:     /new
    defaults: { _controller: "AppBundle:User:new" }

webapp_user_create:
    path:     /create
    defaults: { _controller: "AppBundle:User:create" }
    methods:  POST

webapp_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }

webapp_user_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:User:update" }
    methods:  [POST, PUT]

webapp_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  [POST, DELETE]
